#.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:.#
#                                                               #
#              NDCustom Plugin Configuration file               #
#                                                               #
#.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:.#

# Welcome to NDCustom, a public custom plugin for use on the NotoriousDev servers.
# This plugin has been custom built for the NotoriousDev servers, however it can
# be implemented on other servers with a little Java tweaking. This config file has
# all of the configurable options that the plugin uses, so make sure that all of
# the options are set correctly, otherwise the plugin will not work as expected.

# Do you want the plugin enabled? (This is mainly used for when we are performing checks,
# hence why it is false be default).
enable: false

#Database connection details
database:
  address: localhost
  port: 3306
  database_name: 'test'
  user: 'root'
  password: 'password'

#Join/quit/kick message formats
messages:
  join: '&aJoin &8||&6 {PLAYER}'
  quit: '&cQuit &8||&6 {PLAYER}'
  kick: '&cKick &8||&6 {PLAYER}'
  skyblock-fall: '&c[DEATH] &8||&a {PLAYER} &acouldn''t handle the skyblock...'
  generic-death: '&c[DEATH] &8||&a {PLAYER} &adied of an unknown cause...'
  commands:
    op:
      player: '&cYeah, no.'
      server: '&c[FAIL] &8|| &a{PLAYER} &afailed at using &a/op'
    deop:
      player: '&cYo'' cray cray! You can''t do that!'
      server: '&c[FAIL] &8|| &a{PLAYER} &afailed at using &a/deop'
    reload:
      player: '&cUh-huh. Uh-huh. Nuh-uh. Fgt.'
      server: '&c[FAIL] &8|| &a{PLAYER} &afailed at using &a/reload'
    stop:
      player: '&cNice try, but no.'
      server: '&c[FAIL] &8|| &a{PLAYER} &afailed at using &a/stop'
