#.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:.#
#                                                               #
#              NDCustom Plugin Configuration file               #
#                                                               #
#.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:._.:*~*:.#

# Welcome to NDCustom, a public custom plugin for use on the NotoriousDev servers.
# This plugin has been custom built for the NotoriousDev servers, however it can
# be implemented on other servers with a little Java tweaking. This config file has
# all of the configurable options that the plugin uses, so make sure that all of
# the options are set correctly, otherwise the plugin will not work as expected.

# Do you want the plugin enabled? (This is mainly used for when we are performing checks,
# hence why it is false be default).
enable: false

# You can customise all of the messages that you see in Minecraft in this part of the config.
# Some things to note with these messages:
# &(0-9, a-f) - Colour codes. You can see the colour codes here: http://wiki.ess3.net/mc/
# {PLAYER} - The player in question (e.g. {PLAYER} joined the server = BranicYeti joined the server.)
# {KICKER} - The player who performed the kick/ban.
# {KILLER} - The player/mob that kills {PLAYER}.
# {ITEM} - The item that {PLAYER} is incorrectly using.
messages:
  general:
    join: '&aJoin &8||&6 {PLAYER}'
    quit: '&cQuit &8||&6 {PLAYER}'
    kick: '&cKick &8||&6 {PLAYER}'
  alerts:
    books:
    - 'Rules'
    - 'How2Build'
  chat:
    spam: '&cDude, shut up!'
    caps: '&cTurn off your capslock, bro!'
    time: '&cYou talk too much. Wait 3 seconds between messages.'
  death:
    mob:
    - '&c[DEATH] &8||&a {PLAYER} was absolutely murdered by a {KILLER}!'
    player:
    - '&c[DEATH] &8||&a {KILLER} went hambone on {PLAYER}''s ass!'
    skyblock-fall: # Might rename this in the future. Just a warning. Yeti
    - '&c[DEATH] &8||&a {PLAYER} &acouldn''t handle the skyblock...'
    generic:
    - '&c[DEATH] &8||&a {PLAYER} &adied of an unknown cause...'
  itemblock:
    dispenser: '&cYou may not put {ITEM}''s in a dispenser.'
    throw: '&cYou may not throw {ITEM}''s.'
  commands:
    op:
      disable-use: true
      player: '&cYeah, no.'
      server: '&c[FAIL] &8|| &a{PLAYER} &afailed at using &a/op'
    deop:
      disable-use: true
      player: '&cYo'' cray cray! You can''t do that!'
      server: '&c[FAIL] &8|| &a{PLAYER} &afailed at using &a/deop'
    reload:
      disable-use: true
      player: '&cUh-huh. Uh-huh. Nuh-uh. Fgt.'
      server: '&c[FAIL] &8|| &a{PLAYER} &afailed at using &a/reload'
    stop:
      disable-use: true
      player: '&cNice try, but no.'
      server: '&c[FAIL] &8|| &a{PLAYER} &afailed at using &a/stop'

itemblock:
  dispenser:
    - potion
    - exp_bottle
    - monster_egg
    - monster_eggs
    - arrow
    - snow_ball
    - egg
    - eye_of_ender
    - ender_pearl
    - fireball
    - minecart
    - tnt_minecart
    - hopper_minecart
    - storage_minecart
    - powered_minecart
    - boat
  throw:
    - potion
    - exp_bottle
    - snow_ball
    - egg
    - monster_egg
    - monster_eggs
    - eye_of_ender
    - ender_pearl
    - fireball
    - minecart
    - tnt_minecart
    - hopper_minecart
    - storage_minecart
    - powered_minecart
    - boat
  place:
    - sponge

show-kick-messages: false