# NDCustom plugin.yml - Comments for the benefit of developers in case they don't know what each part of it does #

# Name of the plugin
name: NDCustom
# Main class (The one that extends JavaPlugin, generally.)
main: com.notoriousdev.custom.NDCustom
# Version of the plugin (Make sure that it matches the pom.xml version) (TC Versioning?)
version: "${project.version}"
# Authors of the plugin (Don't just add yourself. An existing author will add you if you deserve it.)
authors: [TheReverend403, BranicYeti]
# Website of NotoriousDev (Not really much use...)
website: http://www.notoriousdev.com
# Commands of the plugin
commands:
  # The base command (Sub-commands do not go here.)
  ndcustom:
    usage: Use /ndcustom reload
    permission: ndcustom.admin
    permission-message: You don't have permission to do that.
    description: Main NDCustom command
    aliases: [ndc]
# Permissions of the plugin (Permissions can and probably will be handled in Permissions.java. Use this for parent permission nodes.)
permissions:
  # The permission node
  ndcustom.admin:
    # Description of the permission node
    description: Grants all permissions to use NDCustom
    # Default permission state (Exceptable values: false, true, OP)
    default: OP
    # Children permission nodes (Permissions that are inherited by this permission node.)
    children:
      # The permission nodes that are inherited (Always true for parent nodes.)
      permission.sub.node: true
